if stairs.has.default then
	stairsplus.api.register_group("default:wood", "stairs_legacy")
	stairsplus.api.register_group("default:junglewood", "stairs_legacy")
	stairsplus.api.register_group("default:pine_wood", "stairs_legacy")
	stairsplus.api.register_group("default:acacia_wood", "stairs_legacy")
	stairsplus.api.register_group("default:aspen_wood", "stairs_legacy")
	stairsplus.api.register_group("default:cobble", "stairs_legacy")
	stairsplus.api.register_group("default:stone", "stairs_legacy")
	stairsplus.api.register_group("default:mossycobble", "stairs_legacy")
	stairsplus.api.register_group("default:stonebrick", "stairs_legacy")
	stairsplus.api.register_group("default:stone_block", "stairs_legacy")
	stairsplus.api.register_group("default:desert_stone", "stairs_legacy")
	stairsplus.api.register_group("default:desert_cobble", "stairs_legacy")
	stairsplus.api.register_group("default:desert_stonebrick", "stairs_legacy")
	stairsplus.api.register_group("default:desert_stone_block", "stairs_legacy")
	stairsplus.api.register_group("default:sandstone", "stairs_legacy")
	stairsplus.api.register_group("default:sandstonebrick", "stairs_legacy")
	stairsplus.api.register_group("default:sandstone_block", "stairs_legacy")
	stairsplus.api.register_group("default:desert_sandstone", "stairs_legacy")
	stairsplus.api.register_group("default:desert_sandstone_brick", "stairs_legacy")
	stairsplus.api.register_group("default:desert_sandstone_block", "stairs_legacy")
	stairsplus.api.register_group("default:silver_sandstone", "stairs_legacy")
	stairsplus.api.register_group("default:silver_sandstone_brick", "stairs_legacy")
	stairsplus.api.register_group("default:silver_sandstone_block", "stairs_legacy")
	stairsplus.api.register_group("default:obsidian", "stairs_legacy")
	stairsplus.api.register_group("default:obsidianbrick", "stairs_legacy")
	stairsplus.api.register_group("default:obsidian_block", "stairs_legacy")
	stairsplus.api.register_group("default:brick", "stairs_legacy")
	stairsplus.api.register_group("default:steelblock", "stairs_legacy")
	stairsplus.api.register_group("default:tinblock", "stairs_legacy")
	stairsplus.api.register_group("default:copperblock", "stairs_legacy")
	stairsplus.api.register_group("default:bronzeblock", "stairs_legacy")
	stairsplus.api.register_group("default:goldblock", "stairs_legacy")
	stairsplus.api.register_group("default:ice", "stairs_legacy")
	stairsplus.api.register_group("default:snowblock", "stairs_legacy")
	stairsplus.api.register_group("default:glass", "stairs_legacy", nil, { ignore_paramtype2 = true })
	stairsplus.api.register_group("default:obsidian_glass", "stairs_legacy", nil, { ignore_paramtype2 = true })
end
